# Date for filtered GTFS files
date: 2019-09-10

# Specify the extents to clip the graph to. These are for Sheffield
# Alternatively, you can provide a named extent (as defined in otp4gb/extents.yml) as a command line -b/--bounds option
extents:
  min_lon: -1.5279
  max_lon: -1.4119
  max_lat: 53.4416
  min_lat: 53.3347

# Specify the osm file to use
osm_file: great-britain-latest.osm.pbf

# Specify the list of GTFS files to process
gtfs_files:
  - GBRail_GTFS.zip
  - EM_GTFS.zip
  - Y_GTFS.zip

# Length of time to search before the travel time,
# if not given then it is calculated based on route availability
time_periods:
  - name: AM
    travel_time: 09:00
    search_window_minutes: 60
  - name: IP
    travel_time: 14:00
    search_window_minutes: 60
  - name: PM
    travel_time: 19:00
    search_window_minutes: 60

# List of lists of modes to include in route calculations
modes:
  # List 1
  - - BUS
    - WALK
  # List 2
  - - TRANSIT
    - WALK

# Factors applied to the respective time / distance when calculation the generalised cost
# times in the generalised cost calculation are in minutes and distances are km
generalised_cost_factors:
  wait_time: 1
  transfer_number: 1
  walk_time: 1
  transit_time: 1
  walk_distance: 1
  transit_distance: 1

# Name of zone centroids file and optional name
# of destination centroids (if different positions)
centroids: centroids.csv
destination_centroids: optional_destination_centroids.csv

# Method used for getting the average generalised cost from all itineraries produced by OTP
iterinary_aggregation_method: mean
max_walk_distance: 10_000

number_of_threads: 10
no_server: no
crowfly_max_distance: 1_000_000

# Optional zone rural urban classification lookup,
# used for adjusting crowfly max distance
ruc_lookup:
  path: ruc_lookup.csv
  id_column: zone_id
  ruc_column: ruc
# List of destinations to exclude when calculating routing
irrelevant_destinations: 
  path: irrelevant_destinations.csv
  zone_column: zone_id
